version: 2
jobs:
  build:
    machine:
      - image: circleci/openjdk:8-jdk-stretch
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo

    environment:
      NODE_PROJECT_FOLDER: /home/circleci/repo
      MAVEN_OPTS: -Xmx2000m
      JAVA_OPTIONS: -Xmx2000m
    steps:
      - checkout
      - run:
          name: Run tests and compile
          command: mvn clean install
      - run:
          name: Where am I?
          command: ls
      - run:
          name: Create runnable JARs
          command: mvn clean compile assembly:single -f master-node-run/pom.xml && mvn clean compile assembly:single -f slave-node-run/pom.xml && mvn clean compile assembly:single -f submaster-node-run/pom.xml
      - run:
          name: Create testing docker containers
          command: docker build -f master-node-run/Dockerfile -t test/node-project-master ./master-node-run && docker build -f slave-node-run/Dockerfile -t test/node-project-slave ./slave-node-run && docker build -f submaster-node-run/Dockerfile -t test/node-project-submaster ./submaster-node-run
      - run:
          name: Run containers tests
          command: mvn -X test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.container.master.MasterThreeSlavesITCase