version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/repo

    environment:
      NODE_PROJECT_FOLDER: /home/circleci/repo
      MAVEN_OPTS: -Xmx2000m
      JAVA_OPTIONS: -Xmx2000m
    steps:
      - checkout
      - run:
          name: Run tests and create jars
          command: mvn clean install
      - run:
          name: Run cache integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.CacheITCase
      - run:
          name: Run core client integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.ClientITCase
      - run:
          name: Run auth session integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.SessionAuthITCase
      - run:
          name: Run auth common tasks integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.AuthCommonTasksITCase
      - run:
          name: Run node info web-based monitoring service integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.NodeMasterMonitoringWebControllerITCase
      - run:
          name: Run auth integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.AuthITCase
      - run:
          name: Run DSA manager integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.NodeDSAManagerITCase
      - run:
          name: Run DSA manager client integration test
          command: mvn test-compile failsafe:integration-test failsafe:verify -f node-ift -Dit.test=ru.babobka.nodeift.NodeDSAManagerClientITCase
