version: '3.5'

services:

  node-postgres:
    image: postgres:9.5
    container_name: node-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - node-project

  master-node:
    image: babobka/node-project-master:1.0
    container_name: master-host
    env_file:
      - .env_master
    environment:
      - WAIT_HOSTS=node-postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    networks:
      - node-project

  slave-node-1:
    image: babobka/node-project-slave:1.0
    container_name: slave-host-1
    env_file:
      - .env_slave
    environment:
      - SLAVESERVERCONFIG_WEBPORT=28080
      - WAIT_HOSTS=master-host:19090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    depends_on:
      - master-node
    networks:
      - node-project

  submaster-slave-node:
    image: babobka/node-project-slave:1.0
    container_name: submaster-slave-host
    env_file:
      - .env_submaster_slave
    environment:
      - SLAVESERVERCONFIG_WEBPORT=28080
      - WAIT_HOSTS=submaster-host:29090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    depends_on:
      - submaster-node
    networks:
      - node-project

  submaster-node:
    image: babobka/node-project-submaster:1.0
    container_name: submaster-host
    env_file:
      - .env_submaster
    environment:
      - WAIT_HOSTS=master-host:19090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    depends_on:
      - master-node
    networks:
      - node-project

networks:
  node-project:
