package ru.babobka.nodeift.container;

import ru.babobka.nodebusiness.debug.DebugBase64KeyPair;
import ru.babobka.nodebusiness.debug.DebugCredentials;
import ru.babobka.nodeconfigs.master.MasterServerConfig;
import ru.babobka.nodeconfigs.slave.SlaveServerConfig;

import java.util.HashMap;
import java.util.Map;

public class ContainerConfigs {


    public static final String MASTER_SERVER_CONFIG_ENV_PREFIX = MasterServerConfig.class.getSimpleName().toUpperCase();
    public static final String SLAVE_SERVER_CONFIG_ENV_PREFIX = SlaveServerConfig.class.getSimpleName().toUpperCase();

    public static final String RMQ_NETWORK_ALIAS = "rmq";
    public static final String POSTGRES_NETWORK_ALIAS = "postgres";
    public static final int DEFAULT_RMQ_PORT = 5672;
    public static final int DEFAULT_POSTGRES_PORT = 5432;

    static final String MASTER_SERVER_NETWORK_ALIAS = "master-host";
    static final int MASTER_CLIENT_PORT = 17070;
    static final int MASTER_WEB_PORT = 18080;
    static final int MASTER_SLAVE_PORT = 19090;

    static final Map<String, String> MASTER_ENV = new HashMap<>();

    static {
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_DBCONFIG_HOST", POSTGRES_NETWORK_ALIAS);
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_MODES_TESTUSERMODE", "true");
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_MODES_CACHEMODE", "false");
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_MODES_SINGLESESSIONMODE", "false");
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PUBKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PRIVKEY", DebugBase64KeyPair.DEBUG_PRIV_KEY);
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_PORTS_SLAVELISTENERPORT", String.valueOf(MASTER_SLAVE_PORT));
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_PORTS_WEBLISTENERPORT", String.valueOf(MASTER_WEB_PORT));
        MASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_PORTS_CLIENTLISTENERPORT", String.valueOf(MASTER_CLIENT_PORT));
    }

    static final Map<String, String> MASTER_RMQ_ENV = new HashMap<>();

    static {
        MASTER_RMQ_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_RMQ_HOST", RMQ_NETWORK_ALIAS);
        MASTER_RMQ_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_RMQ_PORT", String.valueOf(DEFAULT_RMQ_PORT));
    }

    static final Map<String, String> SLAVE_ENV = new HashMap<>();

    static {
        SLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERPORT", String.valueOf(MASTER_SLAVE_PORT));
        SLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERHOST", MASTER_SERVER_NETWORK_ALIAS);
        SLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERBASE64PUBLICKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_SLAVELOGIN", DebugCredentials.USER_NAME);
        SLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PUBKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PRIVKEY", DebugBase64KeyPair.DEBUG_PRIV_KEY);
    }

    static final String SUBMASTER_SERVER_NETWORK_ALIAS = "sub-master-host";
    static final int SUBMASTER_CLIENT_PORT = 27070;
    static final int SUBMASTER_WEB_PORT = 28080;
    static final int SUBMASTER_SLAVE_PORT = 29090;

    static final Map<String, String> SUBMASTER_ENV = new HashMap<>();

    static {
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_DBCONFIG_HOST", POSTGRES_NETWORK_ALIAS);
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_MODES_TESTUSERMODE", "true");
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_MODES_CACHEMODE", "false");
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_MODES_SINGLESESSIONMODE", "false");
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PUBKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PRIVKEY", DebugBase64KeyPair.DEBUG_PRIV_KEY);
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_PORTS_SLAVELISTENERPORT", String.valueOf(SUBMASTER_SLAVE_PORT));
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_PORTS_WEBLISTENERPORT", String.valueOf(SUBMASTER_WEB_PORT));
        SUBMASTER_ENV.put(MASTER_SERVER_CONFIG_ENV_PREFIX + "_PORTS_CLIENTLISTENERPORT", String.valueOf(SUBMASTER_CLIENT_PORT));

        SUBMASTER_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERPORT", String.valueOf(MASTER_SLAVE_PORT));
        SUBMASTER_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERHOST", MASTER_SERVER_NETWORK_ALIAS);
        SUBMASTER_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERBASE64PUBLICKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SUBMASTER_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_SLAVELOGIN", DebugCredentials.USER_NAME);
        SUBMASTER_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PUBKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SUBMASTER_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PRIVKEY", DebugBase64KeyPair.DEBUG_PRIV_KEY);
    }

    static final Map<String, String> SUBMASTERSLAVE_ENV = new HashMap<>();

    static {
        SUBMASTERSLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERPORT", String.valueOf(SUBMASTER_SLAVE_PORT));
        SUBMASTERSLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERHOST", SUBMASTER_SERVER_NETWORK_ALIAS);
        SUBMASTERSLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_MASTERSERVERBASE64PUBLICKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SUBMASTERSLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_SLAVELOGIN", DebugCredentials.USER_NAME);
        SUBMASTERSLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PUBKEY", DebugBase64KeyPair.DEBUG_PUB_KEY);
        SUBMASTERSLAVE_ENV.put(SLAVE_SERVER_CONFIG_ENV_PREFIX + "_KEYPAIR_PRIVKEY", DebugBase64KeyPair.DEBUG_PRIV_KEY);
    }

}
